import { memo, useMemo } from "react";
import {
  ServerComponentInner,
  useStates as useStatesServerComponentInner,
} from "./ServerComponentInner";

export const ServerComponentWrapper = memo(
  () => {
    return (
      <div id="ServerComponentWrapper">
        <div>(Wrapper...)</div>
        <ServerComponentInner />
        <div>(...wrapper!)</div>
      </div>
    );
  },
  () => true
);

ServerComponentWrapper.displayName = "ServerComponentWrapper";

/**
 * This would be generated by the compiler.
 */
export const useNested = () => {
  const statesServerComponentInner = useStatesServerComponentInner();

  return useMemo(
    () => ({
      ServerComponentInner: {
        states: statesServerComponentInner,
        loader: () =>
          import(
            /* webpackChunkName: "ServerComponentInner" */
            "./ServerComponentInner"
          ).then((mod) => mod.ServerComponentInner),
      },
    }),
    [statesServerComponentInner]
  );
};
