import { memo, useCallback, useMemo, useRef } from "react";
import {
  ServerComponentInner,
  useStates as useStatesServerComponentInner,
} from "./ServerComponentInner";

export const ServerComponentWrapper = memo(
  () => {
    return (
      <div id="ServerComponentWrapper">
        <div>(Wrapper...)</div>
        <ServerComponentInner />
        <div>(...wrapper!)</div>
      </div>
    );
  },
  () => true
);

ServerComponentWrapper.displayName = "ServerComponentWrapper";

/**
 * This would be generated by the compiler.
 */
export const useNested = () => {
  const statesServerComponentInner = useStatesServerComponentInner();

  const loadedRef = useRef(false);

  const setLoaded = useCallback(() => {
    loadedRef.current = true;
  }, []);

  const loader = useCallback(
    () =>
      import(
        /* webpackChunkName: "ServerComponentInner" */
        "./ServerComponentInner"
      ).then((mod) => mod.ServerComponentInner),
    []
  );

  return useMemo(
    () => ({
      ServerComponentInner: {
        states: statesServerComponentInner,
        loaded: loadedRef.current,
        setLoaded,
        loader,
      },
    }),
    [statesServerComponentInner, loader, setLoaded]
  );
};
