import { memo, useMemo } from "react";
import { useRecoilValue } from "recoil";
import { textState } from "../state/textState";

export const ServerComponentInner = memo(
  () => {
    const text = useRecoilValue(textState);
    return (
      <div id="ServerComponentInner">
        <div>SERVER? {(typeof window !== "object").toString()}</div>
        <div>TEXT STATE: {text}</div>
      </div>
    );
  },
  () => true
);

ServerComponentInner.displayName = "ServerComponentInner";

/**
 * This would be generated by the compiler.
 */
export const useStates = () => {
  const text = useRecoilValue(textState);

  return useMemo(
    () => [
      {
        state: textState,
        value: text,
      },
    ],
    [text]
  );
};
