import type { NextPage } from "next";
import Link from "next/link";
import { ReactiveHydrationContainer } from "reactive-hydration";
import { RecoilStateSetterButtonsDynamic } from "components/RecoilStateSetterButtons/dynamic";
import { ExampleServerComponentDynamic } from "components/ExampleServerComponent/dynamic";

const Home: NextPage = () => {
  return (
    <div>
      <h1>Home Page</h1>

      <nav>
        <Link href="/other">Other Page</Link>
      </nav>

      <RecoilStateSetterButtonsDynamic />

      {/* This wrapper could be generated by a compiler when we import `ExampleServerComponent`. */}
      <ReactiveHydrationContainer
        Comp={ExampleServerComponentDynamic}
        LazyComp={ExampleServerComponentDynamic}
      />
    </div>
  );
};

export default Home;
